apiVersion: v1
baseDomain: kflowtech.com
metadata:
  name: openshift4

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 2

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}
fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2RwZXRlcnNvcmVkaGF0Y29tMW1sa3NwZGh2a2FzZGQwd2Q1c3R5cHNtaHJjOkhUSU0zUzJLWDRQSzRDUzdZWFVNRUxMRkczUjZVNERZODJFSUgxNjRNWkI3WFdQNkgySjdMNTYyOEdCTVg2TzE=","email":"dpeterso@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2RwZXRlcnNvcmVkaGF0Y29tMW1sa3NwZGh2a2FzZGQwd2Q1c3R5cHNtaHJjOkhUSU0zUzJLWDRQSzRDUzdZWFVNRUxMRkczUjZVNERZODJFSUgxNjRNWkI3WFdQNkgySjdMNTYyOEdCTVg2TzE=","email":"dpeterso@redhat.com"},"registry.connect.redhat.com":{"auth":"NTI2MTQ5MjF8dWhjLTFNTGtzcERoVktBc2REMHdENXN0eXBzbWhSYzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSm1aREUyTmpFeE9UaGlaR0kwWWpoa09XSTFaR1ZsT1RJM1pqVTVNbVUyTnlKOS5mbkJsWV9tbXFVbHN3bXlfY3JSd1BNRXRoNXh5ckkxNUpaWjFaQW95ci0wX1pnSVphd0NSX1hwUEZuQlNvZUl2YUVBbXk0Q1ktQlVrZUhNczYzSTl5Ukw4ZmVEVkp3VVAwQ3J0STlWM1RpbWFES19jWDExTUNyWTJrY2JWRVhRem9TMkFkb2I5VXBFemJoSzQ4LW91amlpZ2Nld1NwdzVkVWdGNC1CZDBtOHVTbFFwbVhxSjZaektIeTBpaVpZV01nT2J6WkJ5UV8tS0FJMkJOU3E4T09BLThGNDFfaE16UVlwYlROMDZLRjZuZGs5SDZjaXF5QlFSS243azBEVFdDZlB0SkpGNGVacEhtT2E0cFJsNWZ0NVZRTXBpbEZwcEVON0RHUW9ZNHAtOU9zWkdNRHh3Rk8tZ0hlWUcwVTFSbF94Q0RSamt6cUp4OTZiOGxONTRWUDhGWkdyV0gzX3lzSWJnYnc4SHNPZmFwWHBRYnlJTVNSR0w1Rmk1Y25ZUUlELTd6aHdnNWRJVGM2Q01RNGtEWG1OVjBpcGpkSnBlVDBXZXMwdTZSUERqV1l6V0xnV2M2STdZSUlWaVVBQVBjSDdVWXE4WndxdFdXVzF0SmdOMlc3N2pSdnV6VDk2ejFNWXJfU1l4Unl1UDUxM3M1YzJZX0dUSFVQY2tlcDlHTWsyMzVjd01FOUVickJMN2JVYjBPVi1jYWNsbDJ5aFlSNGZ5MmRUVUtROEFuYmxzaVVncEE3OE8zNlBYQkMwWFV0RV9lQjVOTFduSmhfUHlFQm01Q3lLblVIUDlIRTEtUF84RE9hdWhDSDZQbzlpRHNsS3d6cXNxb2pWSHlPbmFmSEJGMXJkN0FvLWd3Ylc0VWtYUTJQRHFnaVlIUDZxZUF5VklFc21UN3lXQQ==","email":"dpeterso@redhat.com"},"registry.redhat.io":{"auth":"NTI2MTQ5MjF8dWhjLTFNTGtzcERoVktBc2REMHdENXN0eXBzbWhSYzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSm1aREUyTmpFeE9UaGlaR0kwWWpoa09XSTFaR1ZsT1RJM1pqVTVNbVUyTnlKOS5mbkJsWV9tbXFVbHN3bXlfY3JSd1BNRXRoNXh5ckkxNUpaWjFaQW95ci0wX1pnSVphd0NSX1hwUEZuQlNvZUl2YUVBbXk0Q1ktQlVrZUhNczYzSTl5Ukw4ZmVEVkp3VVAwQ3J0STlWM1RpbWFES19jWDExTUNyWTJrY2JWRVhRem9TMkFkb2I5VXBFemJoSzQ4LW91amlpZ2Nld1NwdzVkVWdGNC1CZDBtOHVTbFFwbVhxSjZaektIeTBpaVpZV01nT2J6WkJ5UV8tS0FJMkJOU3E4T09BLThGNDFfaE16UVlwYlROMDZLRjZuZGs5SDZjaXF5QlFSS243azBEVFdDZlB0SkpGNGVacEhtT2E0cFJsNWZ0NVZRTXBpbEZwcEVON0RHUW9ZNHAtOU9zWkdNRHh3Rk8tZ0hlWUcwVTFSbF94Q0RSamt6cUp4OTZiOGxONTRWUDhGWkdyV0gzX3lzSWJnYnc4SHNPZmFwWHBRYnlJTVNSR0w1Rmk1Y25ZUUlELTd6aHdnNWRJVGM2Q01RNGtEWG1OVjBpcGpkSnBlVDBXZXMwdTZSUERqV1l6V0xnV2M2STdZSUlWaVVBQVBjSDdVWXE4WndxdFdXVzF0SmdOMlc3N2pSdnV6VDk2ejFNWXJfU1l4Unl1UDUxM3M1YzJZX0dUSFVQY2tlcDlHTWsyMzVjd01FOUVickJMN2JVYjBPVi1jYWNsbDJ5aFlSNGZ5MmRUVUtROEFuYmxzaVVncEE3OE8zNlBYQkMwWFV0RV9lQjVOTFduSmhfUHlFQm01Q3lLblVIUDlIRTEtUF84RE9hdWhDSDZQbzlpRHNsS3d6cXNxb2pWSHlPbmFmSEJGMXJkN0FvLWd3Ylc0VWtYUTJQRHFnaVlIUDZxZUF5VklFc21UN3lXQQ==","email":"dpeterso@redhat.com"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4V2c39Rundv5r2m7daPc9ga9X30AezXciSpVeaJ7omvG7/lZde6DGmBeW8zeIWPRa0mnCrfB6N2i5cktsbUt9ZXYQ43g29j+eFHhyBlP3a/5Q97XqEazL3GjVaMJvNUU3Mt5FI+Asn3FHavkPNCXY1xJJYdOY/ZkHtb/sVyuT01NYuyVXhsQ3weAX+T7tB9Oryny6h94KYvxX8oCjln2W02YhkKtkhrRtI1QGBBkPnjxY8ObQnD6K5kN3Mh1x1PKVabZMbcQ8DQvDpy0hsx2AhkCMrFjpH0ucpTmOB3PJ3O9ISNOkZu+/4SFJlMnqrAugdO9SC7WhCadUJaYpz9th 
dpeterson@webservice'
